# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Google Analytics
google_analytics: UAâ€”178277270-1

# Personal info
name: Dean Van Heukelom
title: Software Engineering Student
email: vanheukelomdean@gmail.com

# Social links
# twitter_username: facespics
github_username:  vanheukelomdean
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: deanvanheukelom
# pinterest_username: jekyll
youtube_username: 
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/outside_hs.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Dean Van Heukelom and I'm a student enrolled in Software Engineering at McMaster University. I am currently enrolled in level 4 of 5 in my program after returning from completing 16 months of internships. 
  I am most interested in deep learning, computer vision, sensor fusion and robotics. I am skilled at programming, designing software pipelines, high dimensional data manipulation and web development. 
  <br><br>
  {:refdef: style="text-align: center;"}
    <mark>C++/Java</mark>
    <mark>Python</mark>
    <mark>C</mark>
    <mark>JavaScript</mark>
    <mark>React</mark>
  {:refdef}


# Projects Section
# projects_title: Projects

# Experience Section
experience_title: Work Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Some of my other interests and hobbies are :
   - Sports (hockey, basketball, soccer)
   - Fitness training
   - Watching MOOCs in deep learning and robotics
   - Listening to podcasts - Lex Fridman mostly 

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
